on: [release]

jobs:
  kubeflow_upload_job:
    runs-on: ubuntu-latest
    name: Kubeflow Upload and Run Pipeline
    steps:
    - name: Checkout task
      uses: actions/checkout@master

    - name: npm install
      run: npm install

    - name: Compile
      run: npm run build

    - name: Kubeflow Upload and Run Step
      id: upload-run
      uses: actions/kubeflow-pipeline-github-action@master
      with:
        kubeflowEndpoint: '${{ secrets.KUBEFLOW_ENDPOINT }}'
        bearerToken: '${{ secrets.TOKEN }}'
        kubeflowPipelineTask: 'uploadNew'
        pipelineFilePath: 'tests/pipeline.py.tar.gz'
        newPipelineName: 'testPL-${{ github.run_number }}'
        existingPipelineName: 'testPL'
        versionName: 'newVersion-${{ github.run_number }}'

        runName: 'testRun'
        pipeline: 'testPL-${{ github.run_number }}'
        useDefaultVersion: 'true'
        pipelineVersion: 'newVersion-${{ github.run_number }}'
        pipelineParams: '{"name":"resource_group", "value":"kubeflow-integration-rg"}, {"name":"workspace", "value":"kubeflow-integration-aml"}'
        runDescription: ''
        waitForRunToFinish: 'false'
        experiment: 'useExistingExperiment'
        experimentName: 'testExperiment'
        experimentDescription: ''