on: [push]

jobs:
  kubeflow_upload_job:
    runs-on: ubuntu-latest
    name: Kubeflow Upload and Run Pipeline
    steps:
    - name: Checkout task
      uses: actions/checkout@master

    # - run: npm install

    - name: Kubeflow Upload and Run Step
      id: upload-run
      uses: marts2007/kubeflow-pipeline-github-action@master
      with:
        kubeflowEndpoint: '${{ secrets.KUBEFLOW_ENDPOINT }}'
        bearerToken: '${{ secrets.TOKEN }}'
        kubeflowPipelineTask: 'uploadNew'
        pipelineFilePath: 'action/code/tests/pipeline.py.tar.gz'
        newPipelineName: 'testPL-${{ github.run_number }}'
        existingPipelineName: 'testPL'
        versionName: 'newVersion-${{ github.run_number }}'

        runName: 'testRun'
        pipeline: 'testPL-${{ github.run_number }}'
        useDefaultVersion: 'true'
        pipelineVersion: 'newVersion-${{ github.run_number }}'
        pipelineParams: '{"name":"resource_group", "value":"kubeflow-integration-rg"}, {"name":"workspace", "value":"kubeflow-integration-aml"}'
        runDescription: ''
        waitForRunToFinish: 'false'
        experiment: 'useExistingExperiment'
        experimentName: 'testExperiment'
        experimentDescription: ''
    # Use the outputs from the `Kubeflow Upload and Run Step`
    - name: Get all outputs
      run: |
        echo "Pipeline version id ${{ steps.upload-run.outputs.kf_pipeline_version_id }}"
        echo "Pipeline id ${{ steps.upload-run.outputs.kf_pipeline_id }}"
        echo "Experiment id ${{ steps.upload-run.outputs.kf_experiment_id }}"
        echo "Run id ${{ steps.upload-run.outputs.kf_run_id }}"
